package api

import (
	"time"

	"github.com/tonedefdev/kubecsr/pkg/csr"
)

// KubeCSR represents a Kubernetes CSR and the Kubeconfig's used to create and use the
// newly created user crt and key
type KubeCSR struct {
	// The CertificateRequest that includes details like the user, organization unit
	// region information, and other common fields in x509 Certificate Signing Requests
	CertificateRequest *csr.CSR `json:"certificateRequest" binding:"required"`
	// The time in seconds until the certificate expires. This is only beta for Kubernetes
	// versions 1.22+ enabled with a feature flag
	ExpirationSeconds *int32 `json:"expirationSeconds,omitempty"`
	// In the request body this is the Kubeconfig that's used to approve the Kubernetes CSR
	// In the response body this is the ready-to-use Kubeconfig generated for the requested
	// Kubernetes user
	Kubeconfig string `json:"kubeconfig" binding:"required"`
	// In the response body this is the metadata that is generated by the request
	RequestMetadata RequestMetadata `json:"requestMetadata"`
}

// RequestMetadata is metadata that is generated by the request
type RequestMetadata struct {
	// The time the request was made
	Timestamp time.Time `json:"timestamp"`
	// The requesting IP address from the header field
	RequesterIP string `json:"requesterIP"`
}
